name: CI

on:
  schedule:
    - cron: "0 3 * * 0"
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Lean toolchain via elan
        shell: bash
        run: |
          set -euxo pipefail
          curl -fsSL https://github.com/leanprover/elan/releases/latest/download/elan-init.sh -o elan-init.sh
          bash elan-init.sh -y --default-toolchain none
          echo "$HOME/.elan/bin" >> $GITHUB_PATH
          ~/.elan/bin/elan toolchain install $(cat lean-toolchain)
          ~/.elan/bin/elan default $(cat lean-toolchain)
          ~/.elan/bin/lean --version
          ~/.elan/bin/lake --version || true
      - name: Cache Lake packages
        uses: actions/cache@v4
        with:
          path: .lake/packages
          key: lake-${{ hashFiles('lean-toolchain', 'lake-manifest.json') }}
          restore-keys: |
            lake-
      - name: Lake update
        run: |
          lake update
      - name: Lake build
        run: |
          lake build
      - name: Verify (holes/axioms and theorems)
        run: |
          bash scripts/verify.sh
