name: CI

on:
  push:
    branches: [ main, feat/**, chore/** ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install elan (Lean toolchain)
        uses: leanprover/elan-action@v1

      - name: Cache lake packages
        uses: actions/cache@v4
        with:
          path: |
            .lake
            lake-packages
          key: ${{ runner.os }}-lake-${{ hashFiles('lake-manifest.json') }}
          restore-keys: |
            ${{ runner.os }}-lake-

      - name: Lake build
        run: |
          lake update
          lake build

      - name: Verify (no sorries/axioms; key theorems present)
        run: |
          bash scripts/verify.sh
